final List<String> brtStationsLagos = [
  "Ikorodu Garage Station",
  "Mile 2 Station",
  "Aruna Station",
  "Agric Station",
  "Majidun Ogolonto Station",
  "Majidun Awori Station",
  "Irawo Station",
  "Idera Station",
  "Owode Onirin Station",
  "Mile 12 Station",
  "Ketu Station",
  "Ojota Station",
  "New Garage Station",
  "Maryland Station",
  "Ikeja Station",
  "Idiroko Station",
  "Anthony Station",
  "Oshodi Station",
  "Obanikoro Station",
  "Palmgrove Station",
  "Onipanu Station",
  "Fadeyi Station",
  "Yaba Station",
  "Moshalashi Station",
  "Barracks Station",
  "Stadium Station",
  "Iponri Station",
  "Costain Station",
  "Leventis Station",
  "CMS/Marina Station",
  "TBS Station",
];
