final List<String> brtStationsLagos = [
  "Agric Station",
  "Anthony Station",
  "Aruna Station",
  "Barracks Station",
  "CMS/Marina Station",
  "Costain Station",
  "Fadeyi Station",
  "Idera Station",
  "Idiroko Station",
  "Ikeja Station",
  "Ikorodu Garage Station",
  "Iponri Station",
  "Irawo Station",
  "Leventis Station",
  "Maryland Station",
  "Majidun Awori Station",
  "Majidun Ogolonto Station",
  "Mile 12 Station",
  "Mile 2 Station",
  "Moshalashi Station",
  "New Garage Station",
  "Obanikoro Station",
  "Ojota Station",
  "Onipanu Station",
  "Oshodi Station",
  "Owode Onirin Station",
  "Palmgrove Station",
  "Stadium Station",
  "TBS Station",
  "Yaba Station"
];
